"""empty message

Revision ID: a46ed9682cc1
Revises: 
Create Date: 2022-11-08 20:20:24.461894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46ed9682cc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_info', sa.JSON(), nullable=True),
    sa.Column('download_status', sa.Enum('pending', 'downloading', 'done', 'failed', name='video_download_status'), nullable=True),
    sa.Column('status', sa.Enum('created', 'crawling', 'crawled', 'error', name='video_status'), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_source', 'videos', ['source', 'source_id'], unique=True)
    op.create_index(op.f('ix_videos_download_status'), 'videos', ['download_status'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_download_status'), table_name='videos')
    op.drop_index('ix_video_source', table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
